client_id: ENV['DATABASEDOTCOM_CLIENT_ID']
client_secret: ENV['DATABASEDOTCOM_CLIENT_SECRET']
username: chowfinder@jeffdouglas.com
password: 9KBe67dn2TLcxxvI3lJWp6uTC27ohhdj6fr
debugging: ENV['DATABASEDOTCOM_DEBUGGING']